/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace/index'
import { Route as MarketplaceComponentIdRouteImport } from './routes/marketplace/$componentId'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as TestMarketplaceIndexRouteImport } from './routes/test/marketplace/index'
import { Route as TestComponentsIndexRouteImport } from './routes/test/components/index'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects/$projectId/index'
import { Route as MarketplaceComponentIdEditRouteImport } from './routes/marketplace/$componentId/edit'
import { Route as ProjectsProjectIdComponentsIndexRouteImport } from './routes/projects/$projectId/components/index'
import { Route as ProjectsProjectIdComponentsComponentIdRouteImport } from './routes/projects/$projectId/components/$componentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceComponentIdRoute = MarketplaceComponentIdRouteImport.update({
  id: '/marketplace/$componentId',
  path: '/marketplace/$componentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const TestMarketplaceIndexRoute = TestMarketplaceIndexRouteImport.update({
  id: '/test/marketplace/',
  path: '/test/marketplace/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestComponentsIndexRoute = TestComponentsIndexRouteImport.update({
  id: '/test/components/',
  path: '/test/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/projects/$projectId/',
  path: '/projects/$projectId/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceComponentIdEditRoute =
  MarketplaceComponentIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => MarketplaceComponentIdRoute,
  } as any)
const ProjectsProjectIdComponentsIndexRoute =
  ProjectsProjectIdComponentsIndexRouteImport.update({
    id: '/projects/$projectId/components/',
    path: '/projects/$projectId/components/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdComponentsComponentIdRoute =
  ProjectsProjectIdComponentsComponentIdRouteImport.update({
    id: '/projects/$projectId/components/$componentId',
    path: '/projects/$projectId/components/$componentId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/marketplace/$componentId': typeof MarketplaceComponentIdRouteWithChildren
  '/marketplace': typeof MarketplaceIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/marketplace/$componentId/edit': typeof MarketplaceComponentIdEditRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/test/components': typeof TestComponentsIndexRoute
  '/test/marketplace': typeof TestMarketplaceIndexRoute
  '/projects/$projectId/components/$componentId': typeof ProjectsProjectIdComponentsComponentIdRoute
  '/projects/$projectId/components': typeof ProjectsProjectIdComponentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/marketplace/$componentId': typeof MarketplaceComponentIdRouteWithChildren
  '/marketplace': typeof MarketplaceIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/marketplace/$componentId/edit': typeof MarketplaceComponentIdEditRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/test/components': typeof TestComponentsIndexRoute
  '/test/marketplace': typeof TestMarketplaceIndexRoute
  '/projects/$projectId/components/$componentId': typeof ProjectsProjectIdComponentsComponentIdRoute
  '/projects/$projectId/components': typeof ProjectsProjectIdComponentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/marketplace/$componentId': typeof MarketplaceComponentIdRouteWithChildren
  '/marketplace/': typeof MarketplaceIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/marketplace/$componentId/edit': typeof MarketplaceComponentIdEditRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/test/components/': typeof TestComponentsIndexRoute
  '/test/marketplace/': typeof TestMarketplaceIndexRoute
  '/projects/$projectId/components/$componentId': typeof ProjectsProjectIdComponentsComponentIdRoute
  '/projects/$projectId/components/': typeof ProjectsProjectIdComponentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/marketplace/$componentId'
    | '/marketplace'
    | '/projects'
    | '/marketplace/$componentId/edit'
    | '/projects/$projectId'
    | '/test/components'
    | '/test/marketplace'
    | '/projects/$projectId/components/$componentId'
    | '/projects/$projectId/components'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/marketplace/$componentId'
    | '/marketplace'
    | '/projects'
    | '/marketplace/$componentId/edit'
    | '/projects/$projectId'
    | '/test/components'
    | '/test/marketplace'
    | '/projects/$projectId/components/$componentId'
    | '/projects/$projectId/components'
  id:
    | '__root__'
    | '/'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/marketplace/$componentId'
    | '/marketplace/'
    | '/projects/'
    | '/marketplace/$componentId/edit'
    | '/projects/$projectId/'
    | '/test/components/'
    | '/test/marketplace/'
    | '/projects/$projectId/components/$componentId'
    | '/projects/$projectId/components/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  MarketplaceComponentIdRoute: typeof MarketplaceComponentIdRouteWithChildren
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
  TestComponentsIndexRoute: typeof TestComponentsIndexRoute
  TestMarketplaceIndexRoute: typeof TestMarketplaceIndexRoute
  ProjectsProjectIdComponentsComponentIdRoute: typeof ProjectsProjectIdComponentsComponentIdRoute
  ProjectsProjectIdComponentsIndexRoute: typeof ProjectsProjectIdComponentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/$componentId': {
      id: '/marketplace/$componentId'
      path: '/marketplace/$componentId'
      fullPath: '/marketplace/$componentId'
      preLoaderRoute: typeof MarketplaceComponentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/marketplace/': {
      id: '/test/marketplace/'
      path: '/test/marketplace'
      fullPath: '/test/marketplace'
      preLoaderRoute: typeof TestMarketplaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/components/': {
      id: '/test/components/'
      path: '/test/components'
      fullPath: '/test/components'
      preLoaderRoute: typeof TestComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/$componentId/edit': {
      id: '/marketplace/$componentId/edit'
      path: '/edit'
      fullPath: '/marketplace/$componentId/edit'
      preLoaderRoute: typeof MarketplaceComponentIdEditRouteImport
      parentRoute: typeof MarketplaceComponentIdRoute
    }
    '/projects/$projectId/components/': {
      id: '/projects/$projectId/components/'
      path: '/projects/$projectId/components'
      fullPath: '/projects/$projectId/components'
      preLoaderRoute: typeof ProjectsProjectIdComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/components/$componentId': {
      id: '/projects/$projectId/components/$componentId'
      path: '/projects/$projectId/components/$componentId'
      fullPath: '/projects/$projectId/components/$componentId'
      preLoaderRoute: typeof ProjectsProjectIdComponentsComponentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MarketplaceComponentIdRouteChildren {
  MarketplaceComponentIdEditRoute: typeof MarketplaceComponentIdEditRoute
}

const MarketplaceComponentIdRouteChildren: MarketplaceComponentIdRouteChildren =
  {
    MarketplaceComponentIdEditRoute: MarketplaceComponentIdEditRoute,
  }

const MarketplaceComponentIdRouteWithChildren =
  MarketplaceComponentIdRoute._addFileChildren(
    MarketplaceComponentIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  MarketplaceComponentIdRoute: MarketplaceComponentIdRouteWithChildren,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
  TestComponentsIndexRoute: TestComponentsIndexRoute,
  TestMarketplaceIndexRoute: TestMarketplaceIndexRoute,
  ProjectsProjectIdComponentsComponentIdRoute:
    ProjectsProjectIdComponentsComponentIdRoute,
  ProjectsProjectIdComponentsIndexRoute: ProjectsProjectIdComponentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
